# Generated by Django 3.1.6 on 2021-02-16 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('date_posted', models.DateField(default=datetime.date(2021, 2, 16))),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
